### PR TITLE
Fix undefined attributes found in "casts"

### PR DESCRIPTION
**Pull request by thekonz**
As promised in #15 
I also added tests :)

### CODE REVIEW

**Comment by thekonz** [comment]
I saw that you ignored the composer.lock file which is not what that is for.
Also added an .editorconfig file so other editors know which line endings and tab width to use. (see https://editorconfig.org/)

**Review by Luukdewaaier — APPROVED** [review]
Some great changes! Thanks for the support

**Comment by Luukdewaaier** [comment]
Completely missed the PR 🙁

**Comment by thekonz** [comment]
all good my dude! thx for the merge

**Pull request merged**
